name: Main
on: push

jobs: 
  run_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: format
        run: npm run format

